### ISSUE TITLE
Transparent navigation bar causes UI issues on pre-Q devices

### ISSUE THREAD

**Issue by vbuberen** [beworker/edge-to-edge#1]
Thanks for such a convenient library.

Wanted to report that the way you suggest in the README file works good for screens with no navigation bar, but for devices with good old navigation bar (like we have in Android versions before 9) setting navigation color to transparent causes issues with these navigation bars making navigation buttons almost invisible.

Here is a screenshot taken from your sample app on Android 7:
![Screenshot 2020-04-14 at 19 38 02](https://user-images.githubusercontent.com/13467769/79251268-9ba2a100-7e88-11ea-9dbf-6f82b7347dc6.png)

I guess it should be mentioned in README that such transparent navigation bar should be set only for `values-29` as it is mentioned in Google`s doc: https://developer.android.com/training/gestures/gesturenav#transparent-bars

I will open a PR quit later mentioning it if you don't mind.

**Comment by sergejsha** [comment]
Thanks for reporting this. Transparent navigation bar can cause contrast issues on some `[v23..29)` device indeed. Unfortunately this issue is device specific and can only be fixed for all devices by applying opaque black color instead of transparent one, which is not always wanted. 

I added the [Navigation-Bar-Transparency](https://github.com/beworker/edge-to-edge/wiki/Navigation-Bar-Transparency) wiki page explaining the issue and showing how to solve it. Main readme page was updated as well. No changes to the library or demo app are actually needed IMHO, because the library doesn't control the color of the navigation bar. It's a responsibility of developers using the library.

Hope it helps.

**Comment by vbuberen** [comment]
Thanks. I am quite late with the changes I wanted to add into README.
Yes, I understand that this is device specific. Just wanted to give a heads up, since previously there were no mentions of such possible issues, so it could confuse some devs.

**Comment by vbuberen** [comment]
As to updates to sample app - I would change theme to have this color setting for the navigation bar to values-v29, since some devs might just look at you sample as reference for their code base.
So just a minor addition to play safe even for those, who don't read manual carefully 🙃

**Comment by sergejsha** [comment]
Fair enough. I've just pushed update to navigation bar color for v23 and new v29 colors.xml

**Comment by vbuberen** [comment]
Wow. Thanks for such a quick update.

**Comment by sergejsha** [comment]
You're welcome and thanks for highlighting the issue! Closing it now.
